/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void editStrategyButtonClicked(GButton source, GEvent event) { //_CODE_:editStrategyButton:674897:
  println("editStrategyButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:editStrategyButton:674897:

synchronized public void drawStrategyWindow(PApplet appc, GWinData data) { //_CODE_:strategyWindow:761041:
  appc.background(230);
} //_CODE_:strategyWindow:761041:

public void addButtonClicked(GButton source, GEvent event) { //_CODE_:addButton:621949:
  println("addButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:addButton:621949:

synchronized public void drawAddStrategy(PApplet appc, GWinData data) { //_CODE_:addStrategy:708744:
  appc.background(230);
} //_CODE_:addStrategy:708744:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Live Backtestser");
  editStrategyButton = new GButton(this, 62, 71, 80, 30);
  editStrategyButton.setText("Edit Strategy");
  editStrategyButton.addEventHandler(this, "editStrategyButtonClicked");
  strategyWindow = GWindow.getWindow(this, "Edit Strategy", 0, 0, 240, 240, JAVA2D);
  strategyWindow.noLoop();
  strategyWindow.setActionOnClose(G4P.KEEP_OPEN);
  strategyWindow.addDrawHandler(this, "drawStrategyWindow");
  addButton = new GButton(strategyWindow, 24, 29, 80, 30);
  addButton.setText("Add");
  addButton.addEventHandler(this, "addButtonClicked");
  addStrategy = GWindow.getWindow(this, "Add Strategy", 0, 0, 150, 150, JAVA2D);
  addStrategy.noLoop();
  addStrategy.setActionOnClose(G4P.KEEP_OPEN);
  addStrategy.addDrawHandler(this, "drawAddStrategy");
  strategyWindow.loop();
  addStrategy.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton editStrategyButton; 
GWindow strategyWindow;
GButton addButton; 
GWindow addStrategy;
